[workspace]
members = [
    "automerge",
    "automerge-c",
    "automerge-cli",
    "automerge-test",
    "automerge-wasm",
    "edit-trace",
    "load-trace",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
debug = true
